const ProjectTypes = [
    'Product',
    'Service',
    'App',
    'Game',
    'Event',
    'Group',
    'Initiative',
    'Space',
    'Venue',
    'Art',
    'Installation',
    'Performance',
    'Theatre',
    'Photography',
    'Video',
    'Documentary',
    'Film',
    'Short Film',
    'Animation',
    'Music',
    'Radio',
    'Podcast',
    'Audio',
    'Narrative',
    'Writing',
    'Book',
    'Comic',
    'Publication',
];

export default ProjectTypes;