const ProjectTypes = [
    'Product',
    'Service',
    'App',
    'Game',
    'Event',
    'Group',
    'Initiative',
    'Space',
    'Platform',
    'Venue',
    'Art',
    'Installation',
    'Exhibition',
    'Performance',
    'Theatre',
    'Photography',
    'Video',
    'Documentary',
    'Series',
    'Film',
    'Short Film',
    'Animation',
    'Music',
    'Radio',
    'Podcast',
    'Audio',
    'Narrative',
    'Writing',
    'Book',
    'Comic',
    'Publication',
];

export const ProjectTypeCategories = {
    'Product': [],
    'Service': [],
    'App': ['apps'],
    'Game': ['games'],
    'Event': ['community'],
    'Group': ['community'],
    'Initiative': ['community'],
    'Space': ['community'],
    'Venue': ['community'],
    'Art': ['arts'],
    'Installation': ['design', 'arts'],
    'Exhibition': ['arts'],
    'Performance': ['arts'],
    'Theatre': ['arts'],
    'Photography': ['arts', 'media'],
    'Video': ['arts', 'media'],
    'Documentary': ['media'],
    'Film': ['arts', 'media'],
    'Short Film': ['arts', 'media'],
    'Animation': ['arts', 'media'],
    'Series': ['media'],
    'Music': ['music'],
    'Radio': ['media'],
    'Podcast': ['media'],
    'Audio': ['media'],
    'Narrative': ['media'],
    'Writing': ['media'],
    'Book': ['media'],
    'Comic': ['media'],
    'Publication': ['media'],
};

export default ProjectTypes;