const promptIds = {
    PROJECT_ARCHIVE: 'PROJECT_ARCHIVE',
    PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
    PROJECT_UNARCHIVED: 'PROJECT_UNARCHIVED',
    SHARE_PROJECT: 'SHARE_PROJECT',
    SHARE_PROFILE: 'SHARE_PROFILE',
    SHARE_PROJECT_COMPLETE: 'SHARE_PROJECT_COMPLETE',
    SHARE_PROFILE_COMPLETE: 'SHARE_PROFILE_COMPLETE',
    MAKE_PUBLIC: 'MAKE_PUBLIC',
    MAKE_PRIVATE: 'MAKE_PRIVATE',
    MAKE_PUBLIC_COMPLETE: 'MAKE_PUBLIC_COMPLETE',
    MAKE_PUBLIC_COMPLETE_COPIED: 'MAKE_PUBLIC_COMPLETE_COPIED',
    MAKE_PRIVATE_COMPLETE: 'MAKE_PRIVATE_COMPLETE',
    SIGN_UP: 'SIGN_UP',
    LOG_IN: 'LOG_IN',
    LOG_IN_ERROR: 'LOG_IN_ERROR',
    SIGN_UP_USERNAME_EXISTS: 'SIGN_UP_USERNAME_EXISTS',
    LOGGED_OUT: 'LOGGED_OUT',
}

export default promptIds;