const promptIds = {
    PROJECT_ARCHIVE: 'PROJECT_ARCHIVE',
    PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
    PROJECT_UNARCHIVED: 'PROJECT_UNARCHIVED',
    SHARE_PROJECT: 'SHARE_PROJECT',
    SHARE_PROFILE: 'SHARE_PROFILE',
    SHARE_PROJECT_COMPLETE: 'SHARE_PROJECT_COMPLETE',
    SHARE_PROFILE_COMPLETE: 'SHARE_PROFILE_COMPLETE',
    MAKE_PUBLIC: 'MAKE_PUBLIC',
    MAKE_PRIVATE: 'MAKE_PRIVATE',
}

export default promptIds;