const promptIds = {
    PROJECT_ARCHIVE: 'PROJECT_ARCHIVE',
    PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
    PROJECT_UNARCHIVED: 'PROJECT_UNARCHIVED',

    SHARE_PROJECT: 'SHARE_PROJECT',
    SHARE_PROFILE: 'SHARE_PROFILE',
    SHARE_POST: 'SHARE_POST',
    SHARE_PROJECT_COMPLETE: 'SHARE_PROJECT_COMPLETE',
    SHARE_PROFILE_COMPLETE: 'SHARE_PROFILE_COMPLETE',
    SHARE_POST_COMPLETE: 'SHARE_POST_COMPLETE',

    MAKE_PUBLIC: 'MAKE_PUBLIC',
    MAKE_PRIVATE: 'MAKE_PRIVATE',
    MAKE_PUBLIC_COMPLETE: 'MAKE_PUBLIC_COMPLETE',
    MAKE_PUBLIC_COMPLETE_COPIED: 'MAKE_PUBLIC_COMPLETE_COPIED',
    MAKE_PRIVATE_COMPLETE: 'MAKE_PRIVATE_COMPLETE',

    SIGN_UP: 'SIGN_UP',
    LOG_IN: 'LOG_IN',
    LOG_IN_ERROR: 'LOG_IN_ERROR',

    USERNAME_EXISTS: 'USERNAME_EXISTS',
    SIGN_UP_EMAIL_EXISTS: 'SIGN_UP_EMAIL_EXISTS',
    LOGGED_OUT: 'LOGGED_OUT',
    ADD_PROJECT_ERROR: 'ADD_PROJECT_ERROR',
    SET_ACCOUNT: 'SET_ACCOUNT',
    RESET_PASSWORD: 'RESET_PASSWORD',
    ACCOUNT_READY: 'ACCOUNT_READY',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    FORGOT_PASSWORD_RESET: 'FORGOT_PASSWORD_RESET',
    PASSWORD_RESET: 'PASSWORD_RESET',

    INVALID_IMAGE_TYPE_JPG_PNG: 'INVALID_IMAGE_TYPE_JPG_PNG',
    INVALID_IMAGE_FILESIZE_TOO_LARGE: 'INVALID_IMAGE_FILESIZE_TOO_LARGE',

    DELETE_POST: 'DELETE_POST',
    DELETE_POST_COMPLETE: 'DELETE_POST_COMPLETE',
}

export default promptIds;